### PR TITLE
Add more translation files into test

### PR DESCRIPTION
**Pull request by OrionStar25**
Extended the translation test files in the list, to check if everything still remains consistent.

### CODE REVIEW

**Comment by OrionStar25** [comment]
@sgallagher CentOS is failing. From the logs:
```
One of the configured repositories failed (Unknown),

File /var/cache/yum/x86_64/7/epel/metalink.xml does not exist
Could not parse metalink https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=x86_64 error was 
No repomd file
```

I interpret that a certain repository upstream failed to install itself (?) No problem with the code as such.

**Comment by sgallagher** [comment]
> @sgallagher CentOS is failing. From the logs:
> 
> ```
> One of the configured repositories failed (Unknown),
> 
> File /var/cache/yum/x86_64/7/epel/metalink.xml does not exist
> Could not parse metalink https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=x86_64 error was 
> No repomd file
> ```
> 
> I interpret that a certain repository upstream failed to install itself (?) No problem with the code as such.

Yeah, that's a temporary CI failure, unrelated to this patch. I resubmitted that task which should be fine on the next try.

**Comment by sgallagher** [comment]
> > @sgallagher CentOS is failing. From the logs:
> > ```
> > One of the configured repositories failed (Unknown),
> > 
> > File /var/cache/yum/x86_64/7/epel/metalink.xml does not exist
> > Could not parse metalink https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=x86_64 error was 
> > No repomd file
> > ```
> > 
> > 
> > I interpret that a certain repository upstream failed to install itself (?) No problem with the code as such.
> 
> Yeah, that's a temporary CI failure, unrelated to this patch. I resubmitted that task which should be fine on the next try.

Hmm, it actually looks like there's a real problem on CentOS7, but I'm not sure why it's not happening on Fedora.

**Comment by OrionStar25** [comment]
@sgallagher 
> AssertionError: 'Apache Ant \xc3\xa4r ett Javabibliotek och kommandoradsverktyg vars uppgift det \xc3\xa4r att driva processer som beskrivs i byggfiler som m\xc3\xa5l ut\xc3\xb6kningspunkter som beror p\xc3\xa5 varandra.  Ant tillhandah\xc3\xa5ller ett antal inbyggda uppgifter som g\xc3\xb6r att det g\xc3\xa5r att kompilera, assemblera, testa och k\xc3\xb6ra Javaprogram.  Ant kan \xc3\xa4ven anv\xc3\xa4ndas effektivt f\xc3\xb6r att bygga icke-Javaprogram, till exempel C- eller C++-program.  Mer allm\xc3\xa4nt kan Ant anv\xc3\xa4ndas f\xc3\xb6r att styra alla sorters processer som kan beskrivas i termer av m\xc3\xa5l och uppgifter.' != 'Apache Ant is een Java bibliotheek en commandoregelgereedschap met als doel het sturen van processen beschreven in bouwbestanden zoals doelen en uitbreidingen die van elkaar afhankelijk zijn. Het bekendste gebruik van Ant is het bouwen van Java toepassingen. Ant biedt een aantal ingebouwde taken waarme Java toepassingen gecompileerd, geassembleerd, getest en gedraaid kunnen worden. Ant kan ook effectief gebruikt worden voor het bouwen van niet Java toepassingen, bijvoorbeeld C of C++ toepassingen. Meer in het algemeen kan Ant gebruikt worden voor het besturen van elk type proces dat beschreven kan worden in termen van doelen en taken.'


This assertion is failing for Python 2 in CentOS.

**Comment by OrionStar25** [comment]
@sgallagher I tried all variations of translations for testing in CentOS. 

1. They all pass when the list is provided with 1 test file.
2. In` python2`, a string of 1 language is being compared against a string of another language. Idk how that's possible when the `translation` object is being updated with an `entry` object for each catalog file.
3. Also, this particular test is being skipped in distros such as Arch Linux for just python2. Is it possible that there is nothing wrong with the code and we can skip this test for CentOS too?

**Comment by sgallagher** [comment]
The issue here is that python-babel in CentOS 7 is too old. When reading the `.po` file, it cannot determine the locale properly. As a result, I think we want to go ahead and just exclude these tests on that platform.

**Pull request merged**
