### PR TITLE
Update test-modulemd-merger.c

### PR DESCRIPTION
**Pull request by AarushiSingh09**
Updates for the earlier pr.

### CODE REVIEW

**Comment by AarushiSingh09** [comment]
I have made the changes you requested sir. Is it okay?

**Comment by sgallagher** [comment]
Please do not open new PRs for updates. Instead, apply them to the same branch you were using previously and push that (using `--force` if needed).

That way, the complete history of changes is recorded in a single place and may be useful for future contributors to review.

**Comment by AarushiSingh09** [comment]
Yes Sir I realised it after I made the pr request.  Will keep that in mind
for the future PR.
Thank you so much for the merge.
Can I count it as a contribution when Writing the final application for
outreachy?

**Comment by sgallagher** [comment]
> Yes Sir I realised it after I made the pr request. Will keep that in mind for the future PR. Thank you so much for the merge. Can I count it as a contribution when Writing the final application for outreachy?

Yes, you can record it as a contribution.

**Comment by AarushiSingh09** [comment]
Okay Thank you sir.
I am trying really hard and learning and brushing my skills.
I apologize for not able to work all these days

**Pull request merged**
