### PR TITLE
Print `ninja dist` logs if it fails

### PR DESCRIPTION
**Pull request by sgallagher**
Signed-off-by: Stephen Gallagher <sgallagh@redhat.com>

### CODE REVIEW

**Comment by sgallagher** [comment]
The `ninja dist` output can be long and noisy on success, but we probably want to see those logs when it fails.

**Comment by sgallagher** [comment]
> Why is Rawhide showing error for `translation_helpers`? Does this mean its also failing in the master branch? Btw, this is the same error I was getting in my PR #339 for Rawhide.

That looks like someone broke pytz in Rawhide. It's missing a critical file.

**Comment by OrionStar25** [comment]
> That looks like someone broke pytz in Rawhide. It's missing a critical file.

So should we be ignoring this?

**Comment by sgallagher** [comment]
> > That looks like someone broke pytz in Rawhide. It's missing a critical file.
> 
> So should we be ignoring this?

Yes, you can ignore that for now.

**Pull request merged**
