### PR TITLE
Updated several tests

### PR DESCRIPTION
**Pull request by yashpupneja**
Several tests that were only in python file but needed in the c file have been created using several functions.

### CODE REVIEW

**Comment by yashpupneja** [comment]
Hello sir,
Can you guide how to use docker as I am new to fedora . I just need to
resolve my errors of the code but I need to know how to get started with
docker if you could help me with the same.
Thankyou

**Comment by sgallagher** [comment]
`dnf install docker`, make sure to have sudo privileges and then run the
command.

**Comment by yashpupneja** [comment]
Sir I have already installed docker but I need to know how to use it .
Please guide the commands through which I can work on the docker.
Thankyou

**Comment by sgallagher** [comment]
I have just updated the [README.md](https://github.com/fedora-modularity/libmodulemd/blob/master/README.md#prerequisites) with a missing command. You need to make sure that the docker service is running with `sudo systemctl enable --now docker.service`. After that, you should not need to know anything specifically about docker, as `travis-fedora.sh` contains all the necessary commands.

**Comment by yashpupneja** [comment]
Sir this command is not working and it is giving an error saying "command
not found". Can you guide what to do?
Thankyou

**Comment by sgallagher** [comment]
Not without additional information. You are expected to have a basic
working knowledge of Linux systems. If you do not have that, I recommend
looking for a different Outreachy project.

**Pull request closed without merging**
