### PR TITLE
Enable source-git functionality for Fedora

### PR DESCRIPTION
**Pull request by sgallagher**
Signed-off-by: Stephen Gallagher <sgallagh@redhat.com>

### CODE REVIEW

**Comment by sgallagher** [comment]
@mmathesius Mind giving this a sanity check before I merge it?

**Review by nasirhm — APPROVED** [review]
Looks straightforward.

**Review by mmathesius — COMMENTED** [review]
I don't know much about Packit, so I can't provide much useful feedback at the moment. Besides, this PR was already merged. :wink: 

One question, however. With the addition of `fedora/libmodulemd.spec`, could the top level `libmodulemd.spec.in` eventually go away--or is that the template for `fedora/libmodulemd.spec`?

**Comment by sgallagher** [comment]
> I don't know much about Packit, so I can't provide much useful feedback at the moment. Besides, this PR was already merged. 
> 
> One question, however. With the addition of `fedora/libmodulemd.spec`, could the top level `libmodulemd.spec.in` eventually go away--or is that the template for `fedora/libmodulemd.spec`?

Yes, it can eventually go away, but right now our CI tests are still depending on it. I plan to clean that up when I have time.

**Comment by mmathesius** [comment]
ACK. Thanks!

**Pull request merged**
