### PR TITLE
Only require python2 if installing overrides

### PR DESCRIPTION
**Pull request by sgallagher**
Fixes: https://github.com/fedora-modularity/libmodulemd/issues/257

Signed-off-by: Stephen Gallagher <sgallagh@redhat.com>

### CODE REVIEW

**Comment by larchunix** [comment]
Hi Stephen,

Thanks for your quick PR.

I tried to compile this but it failed during meson test

```
[1/2] Running all tests.
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 112, in run
    return options.run_func(options)
  File "/usr/lib/python3.7/site-packages/mesonbuild/mtest.py", line 805, in run
    return th.doit()
  File "/usr/lib/python3.7/site-packages/mesonbuild/mtest.py", line 555, in doit
    self.run_tests(tests)
  File "/usr/lib/python3.7/site-packages/mesonbuild/mtest.py", line 715, in run_tests
    self.drain_futures(futures)
  File "/usr/lib/python3.7/site-packages/mesonbuild/mtest.py", line 731, in drain_futures
    self.process_test_result(result.result())
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.7/site-packages/mesonbuild/mtest.py", line 257, in run
    cmd = self._get_cmd()
  File "/usr/lib/python3.7/site-packages/mesonbuild/mtest.py", line 237, in _get_cmd
    if self.test.fname[0].endswith('.jar'):
AttributeError: 'NoneType' object has no attribute 'endswith'

[snip]

 58/112 buildopts_python3_debug                 OK       0.20 s 
 59/112 buildopts_python3_release               OK       0.26 s 
FAILED: meson-test 
/usr/bin/meson test --no-rebuild --print-errorlogs
ninja: build stopped: subcommand failed.
```

**Comment by larchunix** [comment]
FYI, I'm using those rules to compile libmodulemd: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=libmodulemd.

With the following changes:
- package version updated to 2.2.2,
- this patch applied
- option `-Dwith_py2_overrides=false` added to meson build.

**Comment by sgallagher** [comment]
I see the problem. I need to have python2 become a disabler() object. I’ll
fix it after lunch.

**Comment by sgallagher** [comment]
I've reworked this patch significantly. It now will always make `python2` a `disabler()` object if `-Dwith_py2_overrides=false`. Additionally, I've changed the default for this option to `false` and distros that need it can enable it explicitly.

@larchunix Would you be willing to create a CI test for Arch Linux similar to those for Fedora, CentOS 7 and openSUSE Tumbleweed currently in the project? That will help me avoid breaking you in the future.

**Comment by larchunix** [comment]
> I've reworked this patch significantly. It now will always make `python2` a `disabler()` object if `-Dwith_py2_overrides=false`. Additionally, I've changed the default for this option to `false` and distros that need it can enable it explicitly.
> 

Perfect, works like a charm now.

Tested-by: Denis Ollier \<larchunix@users.noreply.github.com\>

> @larchunix Would you be willing to create a CI test for Arch Linux similar to those for Fedora, CentOS 7 and openSUSE Tumbleweed currently in the project? That will help me avoid breaking you in the future.

I would be delighted doing so if it can help you. I will work on it and open a PR when it's ready (i.e: I can't give you any ETA).

**Pull request merged**
